---
language: python
services: docker

python: "3.7"

# Ensure pip is present
addons:
  apt:
    packages:
    - python-pip

install:
  # Install required packages
  - pip install molecule yamllint ansible-lint flake8 testinfra docker molecule-docker

env:
  global:
    - ROLE_NAME: avicontroller
  matrix:
    - MOLECULE_DISTRO: centos:8
      MOLECULE_SERVICE_MANAGER: systemd
      MOLECULE_COMMAND: /usr/sbin/init


before_script:
  - cd ../
  - mv ansible-role-$ROLE_NAME avinetworks.$ROLE_NAME
  - cd avinetworks.$ROLE_NAME

script:
  - molecule lint

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
