---
- name: Avi Controller | Services | systemd | Install the Avi Controller service
  include: "systemd/install.yml"
  when: ansible_service_mgr == "systemd"


- name: Avi Controller | Services | {{ ansible_service_mgr }} | Start the service since it's not running |
  service: name=avicontroller enabled=yes state=started
  when: not con_desired_running.stdout
